// This file was generated by Prisma
import { defineConfig } from "prisma/config";

// DATABASE_URL is loaded from root .env via package.json scripts using dotenv-cli

export default defineConfig({
  schema: "prisma/schema",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
