// This file was generated by Prisma
import { defineConfig } from "prisma/config";

// This config is ONLY used by Prisma CLI for migrations
// Migrations require DIRECT_URL (direct connection, port 5432)
// App code uses DATABASE_URL (pooler connection, port 6543) via Supabase client

export default defineConfig({
  schema: "prisma/schema",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prefer DIRECT_URL for migrations (required for schema changes)
    // Fallback to DATABASE_URL only if DIRECT_URL is not set
    url: process.env["DIRECT_URL"] || process.env["DATABASE_URL"],
  },
});
